version: "3.9"

services:

  db:
    build: db
    ports:
      - "5432:5432"
    container_name: postgres_flask
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=flask_hw
